version: 1

rules:
  # Protect centy configuration (read-only)
  - path: ".centy/**"
    access: read
    reason: "Use the centy cli instead of custom editing"

  # Block key files using regex
  - path: "^.*\\.key$"
    type: regex
    access: none
    reason: "Key files contain sensitive credentials"
